const user = {
  results: [
    {
      publicProfile: {
        username: "Joelle_Krajcik",
        email: "Nigel.Zieme93@gmail.com",
        firstName: "Josh",
        lastName: "Lemke",
        pronoun: "They",
        age: 70,
        yearsOfExperience: 5,
        description:
          "Est ratione praesentium quo sint laborum alias repellat. Atque sunt natus omnis molestiae in sed soluta consectetur.",
        isMentor: true,
        isMentee: false,
        role: "Manager",
        department: "Claims",
        location: "Bloomington",
        interests: [
          "Leadership",
          "Graphql",
          "Claims",
          "Data Analytics",
          "React",
        ],
        education: {
          school: "University of Texas at Arlingtion",
          gradDate: "2019-08-15T18:41:30.892Z",
          major: "Psychology",
          degreeType: "Bachelors",
        },
      },
      privateProfile: {
        uuid: "51534634",
        username: "Joelle_Krajcik",
        email: "Nigel.Zieme93@gmail.com",
        firstName: "Josh",
        lastName: "Lemke",
        pronoun: "They",
        age: 70,
        yearsOfExperience: 5,
        description:
          "Est ratione praesentium quo sint laborum alias repellat. Atque sunt natus omnis molestiae in sed soluta consectetur.",
        isMentor: true,
        isMentee: false,
        mentors: [],
        mentees: [
          {
            username: "Arden_Reynolds",
            email: "Forrest_Kreiger@yahoo.com",
            firstName: "Vernon",
            lastName: "Little",
            pronoun: "He",
            age: 27,
            yearsOfExperience: 1,
            description:
              "Fugit cumque excepturi. Ut officia reiciendis tenetur quo est.",
            isMentor: true,
            isMentee: true,
            role: "Intern",
            department: "ET",
            location: "Atlanta",
            interests: [
              "Leadership",
              "AWS",
              "React",
              "Data Science",
              "Machine Learning",
              "Data Analytics",
              "Graphql",
            ],
            education: {
              school: "University of Texas at Arlingtion",
              gradDate: "2021-02-18T20:52:55.576Z",
              major: "Computer Science",
              degreeType: "Bachelors",
            },
          },
          {
            username: "Lincoln.Smitham75",
            email: "Hester.Simonis96@yahoo.com",
            firstName: "Trisha",
            lastName: "Pouros",
            pronoun: "They",
            age: 20,
            yearsOfExperience: 1,
            description:
              "Asperiores optio excepturi sed nesciunt sint labore. Facilis expedita cumque architecto temporibus consequuntur ad natus quo.",
            isMentor: true,
            isMentee: true,
            role: "Intern",
            department: "ET",
            location: "Dallas",
            interests: [
              "Machine Learning",
              "Leadership",
              "Data Analytics",
              "Data Science",
              "AWS",
            ],
            education: {
              school: "University of Texas at Dallas",
              gradDate: "2020-10-09T03:09:38.124Z",
              major: "Music",
              degreeType: "Phd",
            },
          },
          {
            username: "Chet_Kutch27",
            email: "Arch6@gmail.com",
            firstName: "Kayden",
            lastName: "Lubowitz",
            pronoun: "He",
            age: 19,
            yearsOfExperience: 4,
            description:
              "Voluptatem deleniti molestiae. Culpa explicabo sed dolores ipsam at enim ad assumenda.",
            isMentor: true,
            isMentee: true,
            role: "Intern",
            department: "ET",
            location: "Phoenix",
            interests: [
              "AWS",
              "Data Analytics",
              "Claims",
              "Leadership",
              "Graphql",
              "Machine Learning",
            ],
            education: {
              school: "Yale",
              gradDate: "2021-05-25T00:50:58.125Z",
              major: "Computer Science",
              degreeType: "Associates",
            },
          },
          {
            username: "Queen_Glover",
            email: "Merl62@hotmail.com",
            firstName: "Marina",
            lastName: "Stanton",
            pronoun: "She",
            age: 29,
            yearsOfExperience: 2,
            description:
              "Provident expedita hic qui ut. Suscipit blanditiis dolorem reprehenderit natus possimus modi nulla velit.",
            isMentor: false,
            isMentee: true,
            role: "Intern",
            department: "ET",
            location: "Dallas",
            interests: ["AWS", "Claims"],
            education: {
              school: "Yale",
              gradDate: "2020-07-23T20:28:47.199Z",
              major: "Computer Science",
              degreeType: "Associates",
            },
          },
          {
            username: "Ardith8",
            email: "Cortney_Collier62@hotmail.com",
            firstName: "Kyleigh",
            lastName: "Toy",
            pronoun: "They",
            age: 22,
            yearsOfExperience: 3,
            description:
              "Sunt vel qui magni vitae magnam est quasi quia et. Rerum et voluptatem sit et.",
            isMentor: false,
            isMentee: true,
            role: "Intern",
            department: "Data",
            location: "Bloomington",
            interests: [
              "Graphql",
              "Machine Learning",
              "AWS",
              "Data Science",
              "Leadership",
              "React",
              "Data Analytics",
            ],
            education: {
              school: "Harvard",
              gradDate: "2021-06-13T02:40:00.936Z",
              major: "Marketing",
              degreeType: "Bachelors",
            },
          },
        ],
        role: "Manager",
        department: "Claims",
        location: "Bloomington",
        education: {
          school: "University of Texas at Arlingtion",
          gradDate: "2019-08-15T18:41:30.892Z",
          major: "Psychology",
          degreeType: "Bachelors",
        },
      },
    },
  ],
  info: {
    seed: "51f2c57d133170e0",
    results: "1",
    page: "1",
    version: "0.1",
    time: { instruct: 17, generate: 21 },
  },
};

export { user };
